### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-backend#1]
Why?
We need somewhere to store the whiskey information.

**Comment by MikalDr** [comment]
- Queries
- Schema
- How it works

**Comment by Neelzee** [comment]
# Criteria

- [ ] A Database
  - [ ] Dockerized
  - [ ] User-Authentication
    - [ ] Dev-User, for manual queries
    - [ ] Backend-User, for backend queries
