### ISSUE TITLE
Rating Attributes

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-backend#11]
As a user, I want to be able to use predefined sliders with different attributes in my whiskey rating/reviews.

DoD:
- [x] Users can give different slider values along with predefined categories in their whiskey Ratings/Reviews.
- [x] Only admins can add/edit/delete categories.
- [x] Be able to get average attribute values for a specific whiskey.

**Comment by Veggissss** [comment]
DoD met and [merged](https://github.com/Unrated-Limited-Unlimited/ua-backend/pull/20) with dev.

**Comment by Veggissss** [comment]
Reopening this issue; since there seems to be new requirements set by the front-end team:
As illustrated [HERE](https://cdn.discordapp.com/attachments/1199303203234271233/1224748468866912386/image.png?ex=661e9ee5&is=660c29e5&hm=a17f383bd7c060b5fb1188ae2a7065128b1b88f65e4a52798ce5345d9058670a&)

Instead of users adding labels to their reviews such as "Very sweet" they want to be able to express different categories using sliders with number values. For example "Dry - Sweet" with a value 0 indicating Dry and higher values indicating Sweeter taste.

Updated requirements (DoD):
- Users can add different slider categories with a corresponding value.
- Only admins can add new categories

**Comment by Veggissss** [comment]
HELP!?!??!

We still need to know the value range required, 0-5, 1-10 or 0-100 etc..

**Comment by MikalDr** [comment]
@Veggissss the general rating for whiskeys in the app is between 1-5 for a star rating. I believe that the label or characteristic rating can be, maybe between 1-10?

**Comment by Veggissss** [comment]
Sure, 1-10 sounds good.

**Comment by Neelzee** [comment]
We should use floats in backend, and then frontend can convert them however they see fit.
