### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by 591337** [Unrated-Limited-Unlimited/ua-backend#19]
Cors needs to be enabled on the backend. The allowed origin must be set. Can be '*' (can test connecting a locally running frontend to the backend) or 'unrated.no' (frontend must run on that domain in order to test it). Dont know what is best

**Comment by Veggissss** [comment]
I have enabled CORS for:
`
* http://localhost:3000
* https://unrated.no
`
on this test [branch](https://github.com/Unrated-Limited-Unlimited/ua-backend/tree/dev_cors).

Needs further testing to see if it functions correctly.

**Comment by Neelzee** [comment]
Tested with this `dev_cors`, and this worked. When @591337 and I tried this earlier, it did not work, because we used `unrated.no`, without `https`
