### ISSUE TITLE
Get whiskey recommendations

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-backend#2]
As an avid user, I want a list of whiskey recommended for me based on my earlier review tags.

**Comment by Thomas-Johansen** [comment]
DoD:
The user can sort the main whiskey page with a "For you" sorting, which gives recommendations using machine learning.

**Comment by Thomas-Johansen** [comment]
Progress: First iteration is done, but needs testing with mock data

**Comment by Thomas-Johansen** [comment]
Backend functionality now completed, only needs support from the frontside to work
