### ISSUE TITLE
Only test data in production

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-backend#29]
When going to https://api.unrated.no/graphiql and quering:
```graphql
query{
  getWhiskeys{id, title}
}
```
Only the test data/whiskeys shows up, which should not be in production. 
This might be because the environment variable for `MICRONAUT_ENVIRONMENTS` is not set to `prod` .

Adding this to `restart.sh` might solve it:
```sh
export MICRONAUT_ENVIRONMENTS=prod
```

**Comment by Neelzee** [comment]
Will look into, this is for prod? Can be fixed by adding it too the `systemctl`-service file
