### ISSUE TITLE
Image uploading endpoints

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-backend#35]
We need an endpoint where we can upload images to the [file storage server](https://github.com/Unrated-Limited-Unlimited/ua-fiso).

To do so, you could add a normal REST controller to the Controllers package.

Requirements:
- [x] Users can upload profile images.
- [x] Admins can upload whiskey images.

**Comment by 591337** [comment]
@Veggissss I need a way to see if the user has uploaded an image. You can just make img field a boolean or whatever you think is best. (frontend issue [#51](https://github.com/Unrated-Limited-Unlimited/ua-frontend/issues/51))

**Comment by Veggissss** [comment]
@591337 You can now check if user.img is set to null, in this [pull request](https://github.com/Unrated-Limited-Unlimited/ua-backend/pull/39)
