### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by Veggissss** [Unrated-Limited-Unlimited/ua-backend#9]
As a user I want to be able to upload my profile picture for everyone to see.

Criteria:
- A way for users to upload and store images on the server.
- This includes whiskey images as well.

**Comment by 591337** [comment]
Backend should have an endpoint where the client upload an image file. The backend authorizes, uploads to file store and update db

**Comment by Neelzee** [comment]
Frontend also needs to create some functionality for the user to do this without using `cURL`, could be a good first-issue. @MikalDr 

The `ua-fiso`-microservice is working, just needs to be added to the server.

**Comment by Neelzee** [comment]
`ua-fiso` is up and running, can be tested with this cmd:

To get the version
```bash
curl http://localhost:8001/api/meta/version
```

To download a test image:
```bash
curl -o filename.jpg http://localhost:8001/api/img/nils
```

This is still on the server, so you need to `ssh` into the server to test this.
